### ISSUE TITLE
pr issue

### ISSUE THREAD

**Issue by jmk445** [sihyeong671/AID_WEB#21]
포크한 제 레포지토리에 test브랜치로 push 한 후에 pull request를 하려고 하면 

![SE-5e95ce72-547f-431d-916f-df3ceeb9fdab](https://user-images.githubusercontent.com/59995736/227745984-73278043-c56b-4828-862d-3b9ec73be7c9.png)

there isn't anything to compare 라는 화면만 뜨고 pr생성을 할 수 가 없습니다.  변경된 내용이 없어서 그런가 하고 commit을 한번 더 해보려고 하니

![image](https://user-images.githubusercontent.com/59995736/227746164-0aecc37a-0772-4ee3-83b6-14289f24b7aa.png)

On branch feat/test_jmk
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules) 
        modified:   AID_WEB (modified content)

(사진이 화질이 좋지 않아서 코드를 첨부합니다)

no changes added to commit (use "git add" and/or "git commit -a") 

commit이 되지 않습니다. 일단 다른 조치 들을 해보겠습니다.

**Comment by sihyeong671** [comment]
변경내용이 없어서 그런것같습니다. test폴더에 파일을 아무거나 추가하시고 add, commit, push까지 제대로 되었는지 확인 후 재시도 해보세요. fork된 repo에 dev브랜치로부터 branch분기를 해야하는데 fork할때도 main만 하신것같네요 fork시 main만 가져오겠다는 옵션을 제거해야 합니다.
