### ISSUE TITLE
.\backend\crud 폴더 내에 __init__.py가 무엇을 init 하는 코드인지 궁금합니다.

### ISSUE THREAD

**Issue by jmk445** [sihyeong671/AID_WEB#25]
폴더마다 init이 있는 것이 권장되는 구조라서 있는 것인가요?

**Comment by sihyeong671** [comment]
패키지임을 알려주는 코드입니다. 관련해서 [__init__과__all__](https://chancoding.tistory.com/207)을 읽어보세요!
